import Navigation from '@/components/common/Navigation';
import ThemeSwitch from '@/components/common/ThemeSwitch';
import type { Metadata } from 'next';
import { Noto_Sans_KR } from 'next/font/google';
import './globals.css';

const notoSans = Noto_Sans_KR({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={[
          notoSans.className,
          'drawer-content',
          'flex',
          'h-max min-h-[calc(100vh-4rem)]',
          'w-screen',
          'relative',
        ].join(' ')}
        suppressHydrationWarning
      >
        {children}
        <Navigation />

        <ThemeSwitch />
      </body>
    </html>
  );
}
