import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import ThemeSwitch from '@/components/common/ThemeSwitch';
import Navigation from '@/components/common/Navigation';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={[
          inter.className,
          'drawer-content',
          'flex',
          'h-max min-h-[calc(100vh-4rem)]',
          'w-screen',
          'relative',
        ].join(' ')}
        suppressHydrationWarning
      >
        {children}
        <Navigation />

        <ThemeSwitch />
      </body>
    </html>
  );
}
